### ISSUE TITLE
checklist once judges update to `std=c++20`

### ISSUE THREAD

**Issue by lrvideckis** [lrvideckis/programming_team_code#298]
- [ ] change `__` stuff to `<bit>`
  - [ ] bit_ceil https://github.com/lrvideckis/programming_team_code/blob/master/library/range_data_structures/lazy_segment_tree.hpp#L30, https://github.com/lrvideckis/programming_team_code/blob/master/library/range_data_structures/uncommon/merge_sort_tree.hpp#L13
  - [ ] bit_floor https://github.com/lrvideckis/programming_team_code/blob/master/library/range_data_structures/binary_indexed_tree.hpp#L62
  - [ ] bit_width https://github.com/lrvideckis/programming_team_code/blob/master/library/range_data_structures/sparse_table.hpp#L36, https://github.com/lrvideckis/programming_team_code/blob/master/library/range_data_structures/uncommon/disjoint_sparse_table.hpp#L51, https://github.com/lrvideckis/programming_team_code/blob/master/library/range_data_structures/lazy_segment_tree.hpp#L67 - also countr_zero instead of __builtin_ctz
  - [ ] add grep to CI to verify no `__` stuff
- [ ] midpoint
  - [ ] https://github.com/lrvideckis/programming_team_code/blob/master/library/strings/palindrome_query.hpp#L24, impl seg tree, kth smallest, distinct query
- [ ] Remove ssize macro
  - [ ] change to ssize for consistency https://github.com/lrvideckis/programming_team_code/blob/master/library/strings/binary_trie.hpp#L39
  - [ ] add grep to CI to verify no use of `size`
- [ ] range
  - [ ] change arr.begin(), arr.end() to just arr (requires adding `using namespace ranges;` to the template
  - [ ] could be copy_if then transform https://github.com/lrvideckis/programming_team_code/blob/master/library/strings/suffix_array.hpp#L53
  - [ ] could be ranges::views::pairwise https://github.com/lrvideckis/programming_team_code/blob/master/library/strings/suffix_array.hpp#L66-L69
  - [ ] could be transform then inner_product https://github.com/lrvideckis/programming_team_code/blob/master/library/misc/monotonic_stack_related/max_rect_histogram.hpp#L18-L21
  - [ ] could be accumulate https://github.com/lrvideckis/programming_team_code/blob/master/library/graphs/count_paths_per_node.hpp#L35-L36
  - [ ] could be 2 transforms https://github.com/lrvideckis/programming_team_code/blob/master/library/graphs/count_paths_per_length.hpp#L38-L42
  - [ ] views:filter anywhere there's a for(int val : arr) if(...val...) like https://github.com/lrvideckis/programming_team_code/blob/master/library/graphs/strongly_connected_components.hpp#L32-L33
  - [ ] mod int with <=> compare https://codeforces.com/blog/entry/96040?#comment-851247

**Comment by cameroncuster** [comment]
is `bitwidth` better?

**Comment by lrvideckis** [comment]
https://codeforces.com/blog/entry/78931?#comment-644173

**Comment by lrvideckis** [comment]
on second thought, let's not do this.

IMO c++20 just feels kinda hacky/tacky - let's take the ranges library -  it feels as if c++ has been around for too long, and the ranges lib was tacked on (I partly feel this way cuz it's a new namespace)

My criticism is similar to [this](https://codeforces.com/blog/entry/77890#comment-631054) criticism of codeforces most recent rating changes - in that comment, he suggest that instead of fixing evident flaws of the rating system by some hack, to instead switch to a completely different rating system where desirable properties emerge naturally

similarly, maybe the move is to switch to rust instead of c++20
